---

- debug: var=storage_cfg
- debug: var=virsh_cfg

- fail: msg="Please ensure '{{ item.use }}' is set"
  when:
    - not item.val  is defined or item.val  == ""
  with_items:
    - {val: vm_new.name, use: 'VM Target Name'}
    - {val: storage_cfg, use: 'Storage Config Object'}
    - {val: virsh_cfg, use: 'virsh Config Object'}
    - {val: virsh_cfg.version, use: 'OS Version'}
    - {val: virsh_cfg.ip_address, use: 'IP Address'}
    - {val: virsh_cfg.network_domain, use: 'Network Domain'}

- set_fact:
    variant: "{{variants[virsh_cfg.version]}}"
    isoFile: "{{iso_path}}/ubuntu-{{virsh_cfg.version}}-server-amd64.iso"

- set_fact:
    first_boot: "{{first_boot_standard}}"
  when: virsh_cfg.do_proxy|bool == false

- set_fact:
    first_boot: "{{first_boot_proxy}}"
  when: virsh_cfg.do_proxy|bool == true

- set_fact:
    network: bridge:br0
    connect: "qemu:///system"
    vcpus: 1


- name: Create the image
  shell: "virt-install"

#  sudo virt-install --connect {{connect}} -n {{ vm_new.name }} --memory 512 \
#  --cdrom {{ img_file }} --vcpus={{vcpus}} -f /dev/mapper/guest1 --network={{network}} \
#   --vnc --accelerate -v  \
#   --os-type=linux --os-variant=ubuntuXenial

sudo virt-install --connect qemu:///system -n app-worker002 --memory 512 \
  --cdrom /var/lib/libvirt/boot/ubuntu-16.04.3-server-amd64.iso --vcpus=1 --network=bridge:br0 \
  --vnc --accelerate -v --os-type=linux  \
  --disk /mnt/storage0/images/app-worker002/sdb.img,size=100



   #--noautoconsole

#  shell: "kvm ubuntu --netdev {{ netdev }} --part {{ part_file }} --hostname {{ vm_new.name }} --domain {{ vm_new.network_domain }} --dest {{image_path}} --firstboot {{first_boot}}"
#  when: false
# -o
