---

#sed -i 's%us.archive.ubuntu.com%mirrors.gigenet.com/ubuntuarchive/%' /etc/apt/sources.list

- name: Install Packages
  apt: 
    name:
      - qemu-kvm
      - qemu
      - virt-manager
      - virt-viewer
      - libvirt-bin
      - uuid
      - bridge-utils
      - libosinfo-bin
      - ubuntu-vm-builder
      - libguestfs-tools
    state: present
  become: true

# - name: image versions
#   set_fact:
#     versions: "[ '14.04.4', '16.04.1' ]"

# - name: test images
#   stat:
#     path: "{{ iso_path }}/ubuntu-{{ item }}-server-amd64.iso"
#     get_checksum: false
#     get_md5: false
#   become: true
#   with_items: "{{versions}}"
#   register: "r"

# - debug: var=r
# - debug: var=item
#   with_items: "{{r.results}}"

# - name: Downloading images
#   shell: wget -O "{{iso_path}}/ubuntu-{{item.item}}-server-amd64.iso" "http://releases.ubuntu.com/{{item.item}}/ubuntu-{{item.item}}-server-amd64.iso"
#   become: true
#   when: "{{item.stat.exists == false}}"
#   with_items: "{{r.results}}"

- set_fact: 
    virt_groups: 
      - libvirtd
      - netdev
      - "{{libvirt_group}}"

- user:
    name: "{{ target_user }}"
    shell: /bin/bash
    groups: "{{virt_groups}}"
    append: yes
  when: target_user is defined
  become: true

- user:
    name: "{{ remote_user }}"
    shell: /bin/bash
    groups: "{{virt_groups}}"
    append: yes
  when: remote_user is defined
  become: true

- user:
    name: "{{ libvirt_user }}"
    shell: /bin/bash
    groups: "{{libvirt_group}}"
    append: yes
  when: libvirt_user is defined
  become: true
