---

- include: install.yml
  when: do_install|bool == true
  tags:
    - install

- include: create.yml
  when: do_create|bool == true
  tags:
    - create

- include: rename.yml
  when: do_rename|bool == true
  tags:
    - rename

- include: storage_add.yml
  when: do_storage_add|bool == true
  tags:
    - storage
