---

- include_tasks: install.yml
  when: ((['install'] | intersect(flags)) | length > 0)
  tags:
    - install

- include_tasks: create.yml
  when: ((['create'] | intersect(flags)) | length > 0)
  tags:
    - create

- include_tasks: rename.yml
  when: ((['rename'] | intersect(flags)) | length > 0)
  tags:
    - rename

- include_tasks: storage_add.yml
  when: ((['storage_add'] | intersect(flags)) | length > 0)
  tags:
    - storage
