---

- fail: msg="Please ensure '{{ item.use }}' is set"
  when:
    - not {{ item.file }} is defined or {{ item.file }} == ""
  with_items:
    - {file: vm_name_old, use: 'Old VM Name'}
    - {file: vm_name_new, use: 'New VM Name'}

- name: check for enabled
  shell: virsh list --all | grep "{{ vm_name_old }}"
  ignore_errors: true
  register: list_result

- set_fact:
    vm_exists: true
  when: list_result.stdout | search(vm_name_old)

- fail: msg="{{ vm_name_old }} Not Found"
  when: vm_exists|bool == false

- set_fact:
    vm_started: true
  when: list_result.stdout | search("running")

- name: Ensure old is shut down
  shell: virsh shutdown {{ vm_name_old }}
  when: vm_started|bool == true

- name: dump xml
  shell: virsh dumpxml {{ vm_name_old }} > /tmp/{{ vm_name_new }}.xml creates="/tmp/{{ vm_name_new }}.xml"

- name: replace
  shell: sed -i.bak 's/{{vm_name_old}}/{{vm_name_new}}/g' /tmp/{{ vm_name_new }}.xml creates="/tmp/{{ vm_name_new }}.xml.bak"

- name: old path result
  shell:    virsh dumpxml {{vm_name_old}} | grep 'source file' | cut -d\' -f2
  register: old_file_result

- name: new path result
  shell:    grep 'source file' /tmp/{{ vm_name_new }}.xml  | cut -d\' -f2
  register: new_file_result

- set_fact:
    old_file: "{{old_file_result.stdout}}"
    new_file: "{{new_file_result.stdout}}"

- name: stat old_file
  stat:
    path: '{{old_file}}'
    get_checksum: false
    get_md5: false
  register: old_stat

- set_fact:
    do_folder_rename: true
  when: "{{old_stat.stat.exists}}"

- shell: dirname "{{old_file}}"
  register: old_folder_result
  when: do_folder_rename|bool == true

- set_fact:
    old_folder: "{{old_folder_result.stdout}}"
  when: do_folder_rename|bool == true

- shell: dirname "{{old_folder}}"
  register: images_folder_result
  when: do_folder_rename|bool == true

- set_fact:
    images_folder: "{{images_folder_result.stdout}}"
  when: do_folder_rename|bool == true

- set_fact:
    old_folder: "{{images_folder}}/{{vm_name_old}}"
    new_folder: "{{images_folder}}/{{vm_name_new}}"
  when: do_folder_rename|bool == true

- name: Move old to new
  command: mv "{{old_folder}}" "{{new_folder}}"
  when: do_folder_rename|bool == true
  become: true

- name: Undefine "{{vm_name_old}}"
  command: virsh undefine "{{vm_name_old}}"
  when: do_change|bool == true

- name: Define "{{vm_name_new}}"
  command: virsh define "/tmp/{{ vm_name_new }}.xml"
  when: do_change|bool == true

- name: Start "{{vm_name_new}}"
  command: virsh start "{{ vm_name_new }}"
  when: do_change|bool == true
