---
- name: Ensure Required Items
  fail:
    msg: "Please ensure '{{ item.use }}' is set"
  when:
    - not {{ item.var }} is defined or {{ item.var }} | length == 0
  with_items:
    - { var: vm_old, use: "Old VM" }
    - { var: vm_name, use: "New VM" }

- name: Check for enabled
  command: virsh list --all | grep "{{ vm_old }}"
  ignore_errors: true
  register: list_result
  when: true

- name: Test if the VM exists
  set_fact:
    vm_exists: true
  when: list_result.stdout | search(vm_old)

- name: Fail when vm doesn't exist
  fail:
    msg: "{{ vm_old }} Not Found"
  when: not vm_exists

- name: Test if the VM is started
  set_fact:
    vm_started: true
  when: list_result.stdout | search("running")

- name: Ensure old is shut down
  command: virsh shutdown {{ vm_old }}
  when: vm_started

- name: dump xml
  command: virsh dumpxml {{ vm_old }} > /tmp/{{ vm_name }}.xml creates="/tmp/{{ vm_name }}.xml"

- name: replace
  when: true
  lineinfile:
    dest: "/tmp/{{ vm_name }}.xml"
    state: present
    regexp: "{{ vm_old }}"
    line: "{{ vm_name }}"
    backup: true

- name: old path result
  command: virsh dumpxml {{ vm_old }} | grep 'source file' | cut -d\' -f2
  register: old_file_result
  when: true

- name: new path result
  command: grep 'source file' /tmp/{{ vm_name }}.xml  | cut -d\' -f2
  register: new_file_result
  when: true

- name: File Definitions
  set_fact:
    old_file: "{{ old_file_result.stdout }}"
    new_file: "{{ new_file_result.stdout }}"

- name: stat old_file
  stat:
    path: "{{ old_file }}"
    get_checksum: false
    get_md5: false
  register: old_stat

- name: Whether to rename the folder
  set_fact:
    do_folder_rename: true
  when: old_stat.stat.exists

- name: Rename old folder
  command: dirname "{{ old_file }}"
  register: old_folder_result
  when: do_folder_rename

- name: Old Folder Name
  set_fact:
    old_folder: "{{ old_folder_result.stdout }}"
  when: do_folder_rename

- name: Rename images folder
  command: dirname "{{ old_folder }}"
  register: images_folder_result
  when: do_folder_rename

- name: Old Folder Name
  set_fact:
    images_folder: "{{ images_folder_result.stdout }}"
  when: do_folder_rename

- name: Folder Names
  set_fact:
    old_folder: "{{ images_folder }}/{{ vm_old }}"
    new_folder: "{{ images_folder }}/{{ vm_name }}"
  when: do_folder_rename

- name: Move old to new
  command: mv "{{ old_folder }}" "{{ new_folder }}"
  when: do_folder_rename
  become: true

- name: Undefine "{{ vm_old }}"
  command: virsh undefine "{{ vm_old }}"
  when: do_change

- name: Define "{{ vm_name }}"
  command: virsh define "/tmp/{{ vm_name }}.xml"
  when: do_change

- name: Start "{{ vm_name }}"
  command: virsh start "{{ vm_name }}"
  when: do_change
