---

- fail: msg="Please ensure '{{ item.use }}' is set"
  when:
    - not {{ item.var }} is defined or {{ item.var }} == ""
  with_items:
    - {var: vm_old.name, use: 'Old VM'}
    - {var: vm_new.name, use: 'New VM'}

- name: check for enabled
  shell: virsh list --all | grep "{{ vm_old.name }}"
  ignore_errors: true
  register: list_result

- set_fact:
    vm_exists: true
  when: list_result.stdout | search(vm_old.name)

- fail: msg="{{ vm_old.name }} Not Found"
  when: vm_exists|bool == false

- set_fact:
    vm_started: true
  when: list_result.stdout | search("running")

- name: Ensure old is shut down
  shell: virsh shutdown {{ vm_old.name }}
  when: vm_started|bool == true

- name: dump xml
  shell: virsh dumpxml {{ vm_old.name }} > /tmp/{{ vm_new.name }}.xml creates="/tmp/{{ vm_new.name }}.xml"

- name: replace
  shell: sed -i.bak 's/{{vm_old.name}}/{{vm_new.name}}/g' /tmp/{{ vm_new.name }}.xml creates="/tmp/{{ vm_new.name }}.xml.bak"

- name: old path result
  shell:    virsh dumpxml {{vm_old.name}} | grep 'source file' | cut -d\' -f2
  register: old_file_result

- name: new path result
  shell:    grep 'source file' /tmp/{{ vm_new.name }}.xml  | cut -d\' -f2
  register: new_file_result

- set_fact:
    old_file: "{{old_file_result.stdout}}"
    new_file: "{{new_file_result.stdout}}"

- name: stat old_file
  stat:
    path: '{{old_file}}'
    get_checksum: false
    get_md5: false
  register: old_stat

- set_fact:
    do_folder_rename: true
  when: "{{old_stat.stat.exists}}"

- shell: dirname "{{old_file}}"
  register: old_folder_result
  when: do_folder_rename|bool == true

- set_fact:
    old_folder: "{{old_folder_result.stdout}}"
  when: do_folder_rename|bool == true

- shell: dirname "{{old_folder}}"
  register: images_folder_result
  when: do_folder_rename|bool == true

- set_fact:
    images_folder: "{{images_folder_result.stdout}}"
  when: do_folder_rename|bool == true

- set_fact:
    old_folder: "{{images_folder}}/{{vm_old.name}}"
    new_folder: "{{images_folder}}/{{vm_new.name}}"
  when: do_folder_rename|bool == true

- name: Move old to new
  command: mv "{{old_folder}}" "{{new_folder}}"
  when: do_folder_rename|bool == true
  become: true

- name: Undefine "{{vm_old.name}}"
  command: virsh undefine "{{vm_old.name}}"
  when: do_change|bool == true

- name: Define "{{vm_new.name}}"
  command: virsh define "/tmp/{{ vm_new.name }}.xml"
  when: do_change|bool == true

- name: Start "{{vm_new.name}}"
  command: virsh start "{{ vm_new.name }}"
  when: do_change|bool == true
