---
- name: Default variables
  set_fact:
    force: false
    img_file: "{{ base_image_path }}/{{ vm_cfg.storage.secondary.name }}.qcow2"

- name: Delete the image file
  file:
    path: "{{ img_file }}"
    state: absent
  when: force
  become: true

- name: stat {{ img_file }}
  stat:
    path: "{{ img_file }}"
    get_checksum: false
    get_md5: false
  register: old_stat

- name: Create Storage
  command: qemu-img create -f qcow2 -o preallocation=metadata {{ img_file }} {{ vm_cfg.storage.secondary.size }}
  when: not old_stat.stat.exists
  become: true

- name: Set Permissions
  become: true
  file:
    path: "{{ img_file }}"
    state: touch
    mode: 0770
    owner: "{{ libvirt_user }}"
    group: "{{ libvirt_group }}"

- name: Params
  set_fact:
    targetParam: "--target {{ vm_cfg.storage.secondary.name }}"
    sourceParam: "--source {{ img_file }}"
    domainParam: "--domain {{ vm_name }}"
    otherParams: "--driver qemu --subdriver qcow2 --targetbus virtio --config --live"

- name: Attaching Storage to Client
  command: virsh attach-disk {{ domainParam }} {{ sourceParam }} {{ targetParam }} {{ otherParams }}
  become: true
  when: true

- name: Get the xml for the new configuration
  virt:
    name: "{{ vm_name }}"
    command: get_xml
