---

- name: Default variables
  set_fact: 
    force: false
    img_file: "{{ base_image_path }}/{{ vm_cfg.storage.secondary.name }}.qcow2"

- name: Delete the image file
  file: 
    path: "{{ img_file }}"
    state: absent 
  when: force == true
  become: true

- name: stat {{ img_file }}
  stat:
    path: '{{ img_file }}'
    get_checksum: false
    get_md5: false
  register: old_stat

- name: Create Storage
  shell: qemu-img create -f qcow2 -o preallocation=metadata {{ img_file }} {{ vm_cfg.storage.secondary.size }}
  when: old_stat.stat.exists == false
  become: true

- name: Set Permissions
  become: true
  file:
    path: "{{ img_file }}"
    state: touch
    mode: 0770
    owner: "{{ libvirt_user }}"
    group: "{{ libvirt_group }}"


- name: Attaching Storage to Client
  shell: virsh attach-disk --domain {{ vm_name }} --source {{ img_file }} --target {{ vm_cfg.storage.secondary.name }} --driver qemu --subdriver qcow2 --targetbus virtio --config --live
  become: true

- name: Get the xml for the new configuration
  virt: 
    name: "{{ vm_name }}" 
    command: get_xml

