---
    - debug: var=vm_tgt
#    - debug: var=size
#    - debug: var=img_file
#    - debug: var=create_params
#    - debug: var=attach_params

- name: get vm status
  virt: name={{ vm_tgt.name }} command=status
  register: vm_status

- name: Shut down vm instance
  virt: name={{ vm_tgt.name }} command=shutdown
  when: vm_status.status == "running"

- action: virt name={{ vm_tgt.name }} command=status
  register: vm_stat
  until: vm_stat.status == "shutdown"
  retries: 30
  delay: 5
  when: vm_status.status == "running"

- stat: path={{ img_file }}
  register: img_file_stat
  become: true

- name: delete old storage file, if exists
  shell: /bin/rm -f {{ img_file }}
  when: ( img_file_stat.stat.exists )

- name: Create Storage
  raw: qemu-img create {{ create_params }}

- name: Change Storage Owner
  raw: sudo chown libvirt-qemu:kvm {{ img_file }}

- name: Attaching Storage to Client
  raw: virsh attach-disk {{ attach_params }}

- name: Attaching Storage to Client
  virt: name={{ vm_tgt.name }} command=get_xml

- name: Start Up Client
  virt: name={{ vm_tgt.name }} command=start
